stages:
    - test
    - build
    - trigger

test:
  stage: test
  image: golang
  script:
    - go test ./...
variables:
  CLOUD_DOCKER_IMAGE: $ALICLOUD_REGISTRY_HOST/trendyol-abc/$CI_PROJECT_NAME
  
build:
  stage: build
  image:
    name: registry.trendyol.com/platform/base/image/docker:19.03.9-dind
  services:
    - docker:19.03.9-dind
  variables:
    DOCKER_HOST: "tcp://localhost:2375"
    DOCKER_TLS_CERTDIR: ""
  only:
    - master
  script:
    - docker login $GITLAB_REGISTRY_HOST -u $GITLAB_REGISTRY_USER -p $GITLAB_REGISTRY_PASS
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CLOUD_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker login $ALICLOUD_REGISTRY_HOST -u $ALICLOUD_REGISTRY_USER -p $ALICLOUD_REGISTRY_PASS
    - docker push $CLOUD_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA