stages:
#    - test
#    - build
    - trigger

# test:
#   stage: test
#   image: golang
#   script:
#     - go test

# build:
#   stage: build
#   image:
#     name: gcr.io/kaniko-project/executor:debug
#     entrypoint: [""]
#   only:
#     - master
#   script:
#     - echo "{\"auths\":{\"$SF_REGISTRY_URL\":{\"username\":\"$SF_REGISTRY_USER\",\"password\":\"$SF_REGISTRY_PASS\"}}}" > /kaniko/.docker/config.json
#     - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $SF_REGISTRY_URL/sidecache:$CI_COMMIT_SHORT_SHA

trigger:
  stage: trigger
  image:
    name: alpine/git:v2.24.3
  only:
    - master
  script:
    - git config --global user.email "platform@trendyol.com"
    - git config --global user.name "Platform"
    - GIT_URL=https://$GIT_USER:$GIT_PASS@gitlab-sfront.trendyol.com/Base/sidecache-admission-webhook.git
    - git clone $GIT_URL
    - cd sidecache-admission-webhook
    - echo $CI_COMMIT_SHORT_SHA > .build-version.txt
    - git add .build-version.txt
    - git commit -am "Gitlab CI change build version ${CI_COMMIT_SHORT_SHA}"
    - git push $GIT_URL HEAD:master